### ISSUE TITLE
Adding Searching Algorithms in Java

### ISSUE THREAD

**Issue by pabloescoder** [cscodershub/Hacktoberfest-2021#52]
I would like to add the following searching algorithms implemented in JAVA

1. Linear Search
2. Binary Search (In ascending as well as descending sorted array)

Can you please assign it to me? 
Requesting you to add the suitable Hacktoberfest badges as well.
Thank you!

**Comment by Bhavye-Malhotra** [comment]
Hey I think these algos are already in PR's, I would like to request you to contribute something else

**Comment by pabloescoder** [comment]
@Bhavye-Malhotra Sure, do you have any suggestions about what I could work on?

**Comment by Bhavye-Malhotra** [comment]
You can try web dev or some small projects. Also the digital ocean is blacklisting the repos having dsa PRs spammed.

**Comment by pabloescoder** [comment]
Yeah just got to know about it a while back, that's pretty unfortunate. 
I'll work on those domains, thank you!
